### ISSUE TITLE
\typestored: adding a way to print the whole sequence (possibly in a desired order and possibly storing it in an external file)?

### ISSUE THREAD

**Issue by dbitouze** [pablgonz/scontents#2]
# Features request 

(This is a features request, the motivation of which being explained at the end.)

Currently, "[i]f the optional argument [of `\typestored`] is not passed it defaults to the first element stored in the `{⟨seq name⟩}`." What I would expect instead is that it would print the whole concatenated `{⟨seq name⟩}`. For instance, in the following MWE:

```latex
\documentclass{article}
\usepackage{scontents}

\begin{document}
\begin{scontents}[store-env=foo]
bar 1
\end{scontents}
%
\begin{scontents}[store-env=foo]
bar 2
\end{scontents}
%
\begin{scontents}[store-env=foo]
bar 3
\end{scontents}
%
\typestored{foo}
%
\end{document}
```
I would have expected `\typestored{foo}` to display the same as:
```latex
\typestored[1]{foo}
\typestored[2]{foo}
\typestored[3]{foo}
```
that is, verbatim:
> bar 1
>
> bar 2
>
> bar 3

or, **more exactly**, verbatim:
> bar 1
> bar 2
> bar 3

that is as a single block (in consecutive lines, without any extra vertical space between them).

In the same spirit, it would be nice for the optional argument of `\typestored` to let the user specify at once the list of the wished indices in the wished order. For instance, `\typestored[indices={3,1}]{foo}` would display:
> bar 3
> bar 1

As a last suggestion, `\typestored[indices={3,1},write-env={⟨file.ext⟩}]{foo}` would write verbatim:

> bar 3
> bar 1

into the `⟨file.ext⟩` file.

It is probably too late now to change the current syntax but what about introducing these features with a new option?

# Motivation
For a (French) LaTeX FAQ, with source in... LaTeX, I'd like to be able to give for each of the solutions in the answers, successively:

- a possible preamble's addition, e.g.
```latex
\usepackage{amsmath}
```
- an exemplifying code snippet, e.g.
```latex
\begin{align}
  0 & \neq 1 \\
  1 & \neq 0 
\end{align}
```
- a MCE of the solution which:
  - has a fixed structure, say:
  
    ```latex
    \documentclass[french]{article}
    \usepackage[T1]{fontenc}
    \usepackage[utf8]{inputenc}
    \usepackage{lmodern}
    \usepackage[a4paper]{geometry}
    % Here goes the possible preamble's addition
    \usepackage{babel}
    \begin{document}
    % Here goes the code snippet
    \end{document}
    ```
   - includes these preamble's addition and code snippet, in the present case:
   
     ```latex
     \documentclass[french]{article}
     \usepackage[T1]{fontenc}
     \usepackage[utf8]{inputenc}
     \usepackage{lmodern}
     \usepackage[a4paper]{geometry}
     \usepackage{amsmath}
     \usepackage{babel}
     \begin{document}
     \begin{align}
       0 & \neq 1 \\
       1 & \neq 0 
     \end{align}
     \end{document}
     ```
(This is a  simplified example: I'm aware what is added to the preamble should sometimes be inserted after the `babel` package, and even after the `hyperref` package, etc.)

Moreover, the whole MCE stored in an external file would be useful to compile it and include the result as an image in the FAQ.

My current attempt with `scontents` looks like:

```latex
\documentclass{article}
\usepackage{scontents}

% Fix part of a MCE that should go before babel's loading
\begin{scontents}[store-env=mce]
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[a4paper]{geometry}
\end{scontents}

% Fix part of a MCE that should go after (>=) babel's loading
\begin{scontents}[store-env=mce]
\usepackage{babel}
\begin{document}
\end{scontents}

% Fix part of a MCE that should go after its body
\begin{scontents}[store-env=mce]
\end{document}
\end{scontents}

\begin{document}

% Variable part of a MCE that should added to the fixed preamble, before babel's
% loading
\begin{scontents}[store-env=mce]
\usepackage{amsmath}
\end{scontents}

% Variable part of a MCE being the code snippet
\begin{scontents}[store-env=mce]
\begin{align}
  0 & \neq 1 \\
  1 & \neq 0
\end{align}
\end{scontents}

\begin{description}
\item[Preamble's addition]\leavevmode
  \typestored[4]{mce}
\item[Code snippet]\leavevmode
  \typestored[5]{mce}
\item[MCE]\leavevmode
  \typestored[1]{mce}%
  \typestored[4]{mce}%
  \typestored[2]{mce}%
  \typestored[5]{mce}%
  \typestored[3]{mce}%
\end{description}

\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/104095273-45875080-5296-11eb-8089-c8a79a2d4a6b.png)

**Comment by dbitouze** [comment]
# Additional features request

It would also be nice to provide a way to combine multiple sequences. With the first example above, providing something such as `\typestored{[1]foo,[2]{bar},[3]{foo}}` in order to get, as a single block, what results from:
```latex
\documentclass{article}
\usepackage{scontents}

\begin{document}
\begin{scontents}[store-env=foo]
foo 1
\end{scontents}
%
\begin{scontents}[store-env=foo]
foo 2
\end{scontents}
%
\begin{scontents}[store-env=foo]
foo 3
\end{scontents}
%
\begin{scontents}[store-env=bar]
bar 1
\end{scontents}
%
\begin{scontents}[store-env=bar]
bar 2
\end{scontents}
%
\begin{scontents}[store-env=bar]
bar 3
\end{scontents}
%
\typestored[1]{foo}
\typestored[2]{bar}
\typestored[3]{foo}
\end{document}
```

This could be of course generalized to something like:

```latex
\typestored{{[3,1]{foo},[2,3,1]{bar},[5-12]{foo}},write-env={⟨file.ext⟩}
```
:smile:

# Motivation
It would be very helpful in my use case since the fixed templated MCE is likely to be used several times because of several answers in the same file:
```latex
\documentclass{article}
\usepackage{scontents}

% Fix part of a MCE that should go before babel's loading
\begin{scontents}[store-env=mce]
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[a4paper]{geometry}
\end{scontents}

% Fix part of a MCE that should go after (>=) babel's loading
\begin{scontents}[store-env=mce]
\usepackage{babel}
\begin{document}
\end{scontents}

% Fix part of a MCE that should go after its body
\begin{scontents}[store-env=mce]
\end{document}
\end{scontents}

\begin{document}

\section{First annswer}
% Variable part of a MCE that should added to the fixed preamble, before babel's
% loading
\begin{scontents}[store-env=mce-1]
\usepackage{amsmath}
\end{scontents}

% Variable part of a MCE being the code snippet
\begin{scontents}[store-env=mce-1]
\begin{align}
  0 & \neq 1 \\
  1 & \neq 0
\end{align}
\end{scontents}

\begin{description}
\item[Preamble's addition]\leavevmode
  \typestored[1]{mce-1}
\item[Code snippet]\leavevmode
  \typestored[2]{mce-1}
\item[MCE]\leavevmode
  \typestored[1]{mce}%
  \typestored[1]{mce-1}%
  \typestored[2]{mce}%
  \typestored[2]{mce-1}%
  \typestored[3]{mce}%
\end{description}

\section{Second annswer}
% Variable part of a MCE that should added to the fixed preamble, before babel's
% loading
\begin{scontents}[store-env=mce-2]
\usepackage{amsmath}
\end{scontents}

% Variable part of a MCE being the code snippet
\begin{scontents}[store-env=mce-2]
\begin{flalign}
  0 & \neq 1 \\
  1 & \neq 0
\end{flalign}
\end{scontents}

\begin{description}
\item[Preamble's addition]\leavevmode
  \typestored[1]{mce-2}
\item[Code snippet]\leavevmode
  \typestored[2]{mce-2}
\item[MCE]\leavevmode
  \typestored[1]{mce}%
  \typestored[1]{mce-2}%
  \typestored[2]{mce}%
  \typestored[2]{mce-2}%
  \typestored[3]{mce}%
\end{description}

\end{document}
```

**Comment by pablgonz** [comment]
@dbitouze As I told you by mail, now that I have taken the time to read (carefully) your request, I will develop it in parts (it is a bit long :)

> I would have expected `\typestored{foo}` to display the same as:
> ...
> that is as a single block (in consecutive lines, without any extra vertical space between them).

I think that for the first part you could try to implement a _key_ something like `range = start - end` or `range = {start, end}` that fulfills the conditions, of course, the presentation of the contents would have to be consecutive (`start < end`).

> In the same spirit, it would be nice for the optional argument of `\typestored` to let the user specify at once the list of the wished indices in the wished order. For instance, `\typestored[indices={3,1}]{foo}` would display:
> 
> > bar 3
> > bar 1

And here I think you could also implement something with only two arguments a _key_ of the type `index = {start, end}` .

Both seem to me excellent additions to `scontents`. On these two points I think an extension to `\typestored` can be made, of course, at the moment it is only in my mind :)

> As a last suggestion, `\typestored[indices={3,1},write-env={⟨file.ext⟩}]{foo}` would write verbatim:
> 
> > bar 3
> > bar 1
> 
> into the `⟨file.ext⟩` file.

This one is more complicated, getting `expl3` to write to external files was a pain in the ... (I think I aged a couple of years trying), and it would break the command name :( ... of course you can always resort to using `*` and try something, but, I don't see it as easy.

> It is probably too late now to change the current syntax but what about introducing these features with a new option?

It's never too late, the first two would not break the current function of the command, with the last one I will keep silent for now :) 

> For a (French) LaTeX FAQ, with source in... LaTeX, I'd like to be able to give for each of the solutions in the answers, successively:
> 

That's one of the purposes for which it was designed, I use it in the same way, I could no longer remember the names of all the example files I used (nor could I think of new ones). What better than having them loaded in memory :)

The _Additional features request_ I do not see it feasible (for now), it depends on whether the previous ones can be implemented, so I will not pronounce on this point.

Anyway, this is just in my mind for now, @PhelypeOleinik  what do you think about it?

**Comment by polgab** [comment]
I strongly support the new features suggested by @dbitouze  (I came to this site with the idea of requesting these same features).

I will add two new features:

1. it would be useful to know the number of lines memorized by the `scontents` environment (and possibly written in an external file) via an expandable macro like `\numberoflines[index={start,end}]{foo}`.
2. add the new boolean option `append` (combined with `write-env` or `write-out`) to _append_ the content to an external file.

**Comment by pablgonz** [comment]
I think this request looked much simpler in my head than in the implementation as such, for now it will have to wait for version 2.1 and possibly implement it in parts...but I'm working on it :D

**Comment by pablgonz** [comment]
@dbitouze Full implement (https://github.com/pablgonz/scontents/releases/tag/v2.1)
