### ISSUE TITLE
New general environment with arguments

### ISSUE THREAD

**Issue by lvjr** [pablgonz/scontents#5]
I would like to create a new environment with an optional argument and  a mandatory argument. If there are no verbatim contents, I could use `+b` argument type to collect contents:
```latex
\NewDocumentEnvironment{myenv}{o m +b}{
  do something with #1, #2 and #3
}{}
```
But `\NewDocumentEnvironment` doesn't support multiline verbatim contents. Could `scontents` provide this feature, so that I could write e.g.
```latex
\NewScontentsEnvironment{myenv}[2][]{
  do something with #1, #2 and \StoredContents
}
```
Thank you very much!

**Comment by lvjr** [comment]
See also this issue https://github.com/latex3/latex3/issues/591

**Comment by pablgonz** [comment]
Hi @lvjr, you know I have read this a lot of times and I think it is not possible (without major changes) to adjust `scontents` to get what you want, what I do see more feasible is that you can adapt the `filecontensdef` package code to your requirements.

**Comment by lvjr** [comment]
Thank you for the suggestion.
